### PR TITLE
Mitigation for docker-compose volume issue

### PR DESCRIPTION
**Pull request by tomlinton**
This should mostly solve #34.

- Moves `node_modules` for `origin-dapp` out of a volume so `docker-compose build origin-dapp` will work correctly.
- Adds an `npm install` to `origin-js` startup to make sure dependencies are always correct. I couldn't stop using a volume for `node_modules` for `origin-js` because they are shared between containers. I wanted to avoid doing this but it is better than needing to remove/rebuild all containers/volumes.
- Stopped using package-lock.json files because they were not updated in some of the develop branches which caused integrity errors.
- Added polling to watch to hopefully increase reliability of reloads on code changes.
- Add a clean flag to install.sh to clear out all containers/volumes if people run into trouble.

### CODE REVIEW

**Comment by tomlinton** [comment]
Yep `package-lock.json` basically pins an install at an exact version and verifies the hash of the installed module. Something got out of sync a few days ago and a few people turned up with integrity errors. The issue may be exacerbated by the way Docker caches things during the build. I couldn't reproduce so I'm honestly not sure of the exact cause. I asked people to remove the `package-lock.json` from the project that was failing and that resolved it.

I reasoned that during development slightly different versions of packages shouldn't matter, I suspect it'll be better than having builds fail because of this. I'm also not a node pro though, so keen to hear any other thoughts on it!

**Comment by jordajm** [comment]
Yes, IMO we should keep `package-lock.json` files and just make sure that developers are checking in their auto-generated changes to `package-lock.json` when they push changes. It can sometimes be a pain to maintain the file, but without it we're flying blind on what versions of the dependencies were used to make a working version of the app at any given time.

**Comment by tomlinton** [comment]
I hear you. I'm shooting for a development environment that always works so my thinking was that the package-lock.json issue will crop up more than frequently than issues caused by not using the exact versions. Particularly because if a package-lock.json is incorrect it'll only be an issue for new developers as regular developers aren't usually reinstalling their dependencies. I've changed it to use package-lock.json again anyway, and we can always revisit if it becomes too much of an issue.

**Comment by tomlinton** [comment]
Anyone with an itchy finger want to click that merge button? There is a few important fixes in here. :grin:

**Pull request merged**
