### PR TITLE
Fix messaging config

### PR DESCRIPTION
**Pull request by franckc**
There was a typo in IPFS_MAX_CONNECTIONS which I think was causing it to not be set properly.
Also, per @crazybuster's recommendation, I increased default value to 16k
@tomlinton What is the value defined in EnvKey ? (I don't have access to view it). Could you set it to 16k as well for staging, prod and dev ?

Separately, I also noticed the MESSAGING_NAMESPACE might not be set consistently for prod:
 - the backend uses origin:<namespace> (see [template](https://github.com/OriginProtocol/origin-box/blob/master/deployment/kubernetes/charts/origin/templates/messaging.statefulset.yaml#L45)).
 - the DApp prod deployment uses just "origin" (see [Dapp prod container config](https://github.com/OriginProtocol/origin-box/blob/master/deployment/dockerfiles/prod/origin-dapp#L21)).
@tomlinton Could you confirm I'm reading this correctly ? If yes, them pls lmk and I'll fix in this PR as well.

### CODE REVIEW

**Comment by tomlinton** [comment]
Thanks @franckc! 

The fix is good but we are currently using an external IPFS server based on the Go implementation of IPFS (go-ipfs) rather than the OrbitDB server creating its own IPFS server based on the JS implementation of IPFS (js-ipfs). This setting is for the js-ipfs implementation. Previously we only used js-ipfs but the go-ipfs results on a much cleaner setup for us. I know @crazybuster had some issues with go-ipfs previously but was unable to pin it down. Did we run into an issue somewhere that brought this up?

EnvKey is no longer used for the DApp. We just build static JS files and don't serve them via webpack so we can't read variables at runtime anymore. All environment variable config has to happen in the dockerfiles. The reason for this is that webpack is much slower than serving static JS. We should remove the EnvKey DApp settings just to avoid confusion.

Good catch on the namespaces! I fixed the template. My thinking was we'd use `origin:dev` for dev, `origin:staging` for staging and just `origin` for production.

**Comment by crazybuster** [comment]
Umm.. we should probably change the actual config for live for the IPFS_MAX_CONNECTIONS.

Also @tomlinton for we're currently not using go-ipfs for our orbit-server. As of last I checked, go-ipfs was refusing to send db updates after the initial update for orbit db server. It actually looked like a low level pubsub publish issue on topics with multiple messages in it. Haven't got a chance to really pin it down in terms of the libraries but it looks like one of the really low level p2p relay ones:(

**Comment by crazybuster** [comment]
@franckc @tomlinton correction we SHOULD not be using go-ipfs currently, it will not work past the first few messages(I have reproduced this issue with ambert in the past, seems like it did not get relayed).

Also I created an issue on this, but in order for go-ipfs to work, pinning must be also enable or else the entire DB goes away in a day due to gc!

**Comment by tomlinton** [comment]
We are currently using go-ipfs. I had issues with js-ipfs, it won't daemonize correctly and so we can't run it outside of the messaging container which causes some deployment complications. My thinking was we'd use go-ipfs and if any issues arose we couldn't address we'd revert to js-ipfs. I don't think we've run into any problems yet? I'll revert the deployment to js-ipfs anyway. There isn't really enough time to test it out. I'll add the changes to this PR @franckc.

**Comment by crazybuster** [comment]
@tomlinton Currently messaging is not working on demo.originprotocol.com. In my testing, the first few topics will be sent, but then the pubsub will hang on that connection and db messages will not be pushed along. There's also the pinning issue that I wrote up as well in that the db will disappear after a day if not pinned.

I can attached ambert's config from before in terms of daemonizing.  I think he was just running it as a simple process under systemctl. I can paste that config if needs be. Otherwise, there's also an issue of how peer id are retrieved from js-ipfs. It's different.

**Pull request merged**
