### PR TITLE
Hidden Featured listings configuration

### PR DESCRIPTION
**Pull request by sparrowDom**
###Description
Just adding configuration for hidden and featured listings

**Dependant Pull Request**: https://github.com/OriginProtocol/origin-dapp/pull/645

### CODE REVIEW

**Comment by sparrowDom** [comment]
@franckc  in the other PR @wanderingstan proposed a great idea to use git branches instead of gist files like so: https://github.com/OriginProtocol/origin-dapp/blob/master/src/actions/Listing.js#L42-L50

We could pull it off without the need for environmental variables, and can close this PR. So hide/feature lists would reside in github branches and would be globally configured for a specific network id.

**Comment by franckc** [comment]
Using git makes lot of sense. Should we have 1 file per network ?
Like for example hidden_1.txt for mainnet, hidden_4.txt for rinkeby ?

**Comment by sparrowDom** [comment]
Yeah exactly like that

**Comment by wanderingstan** [comment]
@franckc , yes. In the old way we just [appended the network id to the filename](https://github.com/OriginProtocol/origin-dapp/blob/master/src/actions/Listing.js#L45), which should still work. Only different now is that we have the network id permanently set via `ETH_NETWORK_ID`.

**Comment by sparrowDom** [comment]
We will be using git branches instead of gist files. This PR is no longer needed

**Pull request closed without merging**
